// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPANa8Nn2M2tEJsa535DzwFsMp3vLSS_c',
    appId: '1:949326465131:web:5446c9238d3e1d0e88c92e',
    messagingSenderId: '949326465131',
    projectId: 'oncoguardian-d9811',
    authDomain: 'oncoguardian-d9811.firebaseapp.com',
    storageBucket: 'oncoguardian-d9811.firebasestorage.app',
    measurementId: 'G-70Y4QF329X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmqJVPrjT0FekGrHdidAqfwgdPTXHQfoE',
    appId: '1:949326465131:android:ab1d4c03bed9cbec88c92e',
    messagingSenderId: '949326465131',
    projectId: 'oncoguardian-d9811',
    storageBucket: 'oncoguardian-d9811.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATEY9srarY6D05sGJSoVzolqfsMS-R4Qw',
    appId: '1:949326465131:ios:08b797a891f5c2b588c92e',
    messagingSenderId: '949326465131',
    projectId: 'oncoguardian-d9811',
    storageBucket: 'oncoguardian-d9811.firebasestorage.app',
    iosBundleId: 'com.app.oncoguardian',
  );
}
